// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fdrthucinoyteujimwsy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZkcnRodWNpbm95dGV1amltd3N5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg1NzAzNzgsImV4cCI6MjA1NDE0NjM3OH0.Vt1npgg4TQu_ShVpk62X9Fv2gb_QhQ4q9owDA31Rj_Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);